<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org"
         xmlns:xsi="http://w3.org"
         xsi:schemaLocation="http://apache.org https://apache.org">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>com.example.platform</groupId>
        <artifactId>ecommerce-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <!-- ⚠️ Ensure this artifactId matches its respective folder name -->
    <artifactId>api-gateway</artifactId>

        <dependencies>
    <!-- 1. The Core Gateway Starter (DO NOT use spring-boot-starter-web here) -->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-gateway</artifactId>
    </dependency>

    <!-- 2. Eureka Client Discovery -->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    </dependency>
    <!-- 3. Explicit Load Balancer for routing resolution -->
        <!-- we first need to fix why your API Gateway (port 8080) is
			throwing 404 errors. If the gateway doesn't route traffic correctly,
			a frontend application won't be able to talk to your services.-->
		<dependency>
	<groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-loadbalancer</artifactId>
		</dependency>
<!--rate limiter 5 in 1sec-->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
</dependency>

    </dependencies>
</project>
