server:
  port: 8761 #(Eureka) | 8761 (Standard Eureka port)

spring:
  application:
    name: service-registry
  cloud:
    inetutils:
      use-only-site-local-interfaces: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
