server:
  port: 8080 #(The only port the frontend hits)

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      locator:
          enabled: true
          lower-case-service-id: true # Automatically maps uppercase Eureka IDs to lowercase lookups [1]
      routes:
        # 1. Route to Order Service (when needs/if necessary)
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          #  MOVED AND ALIGNED DIRECTLY UNDER THE ROUTE PREDICATE rate limiter
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2    # Lower to 2 requests per second
                redis-rate-limiter.burstCapacity: 2    # Lower burst space to 2 tokens
                key-resolver: "#{@userKeyResolver}"

        # 2. Route to Product Service
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        # 3. Route to Inventory Service
        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
            
        # 4. Route to Customer Service (Example of adding more services!)
        - id: customer-service-route
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        # 5. Route to Payment Service (Example of adding more services!)
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**    
       #6. 
 # 🔐 Add this block to Route to Payment Service authentication traffic
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**            
  #7.
   # 📊 Add this block to route inventory traffic
        - id: inventory-service-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/erp/inventory/**
            
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/      #mult server instances for this prj