server:
  port: 8083

spring:
  application:
    name: product-service
  
  # 🔌 MongoDB Connection URI (Creates 'product_db' automatically on first insert)
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db
      
  security:
    oauth2:
      resourceserver:
        jwt:
          # Fixed property name for Spring Boot validation signatures
          secret-key: "SagarWorkspaceSskSecretKeyForPolyglotSaasErp"

# 📡 Fixed indentation alignment for Eureka Client connection routing
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
